### ISSUE TITLE
pause

### ISSUE THREAD

**Issue by sari777** [WanderingPhilosopher/VanBitCrackenRandom2#1]
great program, but can you please elaborate the word "pause" in the command.  it is function or you just write as guide.

**Comment by marssystems** [comment]
Pause stops the CMD window from closing when the program finishes or has an error.

**Comment by WanderingPhilosopher** [comment]
> thanks, but how to write the command of pause with full command.

I'm not sure what you mean. But in your text editor, you would supply whatever flags for the program and then hit return. You should now be on the second line in the text editor, that's where you type "pause". It just stops the cmd window from closing once the program finishes scanning a range, finds all the targets, or has an error.

**Comment by sari777** [comment]
thanks. i will check it out
