### ISSUE TITLE
question

### ISSUE THREAD

**Issue by unclevito2017** [WanderingPhilosopher/VanBitCrackenRandom2#10]
what does (lookup size 4) mean

**Comment by sari777** [comment]
> what does (lookup size 4) mean

can you please tell, which cuda version is necessary for this vbcr.exe.?

**Comment by unclevito2017** [comment]
If you are using a RTX4090 you need Cuda 11.8 so you can use Cuda 11.8 for older cards also as it is backward compatible and should work on other Nvidia cards. As for lookup size I asked this also and got no answer but I think that applies if you use the -i option and have a text file containing multiple prefixes to lookup instead of looking for a single prefix in the command line. The more prefixes you lookup the slower the speed I believe

**Comment by sari777** [comment]
ok right. on cuda 12. rtx 4090. it is saying cuda runtime version is insufficient for running. version 35.

**Comment by sari777** [comment]
for lookup size, i think you are working on puzzle 130. but i prefer keyhunt rather than this one if we have public key.

**Comment by sari777** [comment]
also not working on 11.8 cuda 4090.

**Comment by unclevito2017** [comment]
go here https://www.nvidia.com/download/index.aspx   and select your operating system and card type you will definitely install what version you need then

**Comment by sari777** [comment]
ok sir.thanks

**Comment by sari777** [comment]
> go here https://www.nvidia.com/download/index.aspx and select your operating system and card type you will definitely install what version you need then. You need to ensure that your driver version matches or exceeds your CUDA Toolkit version

can you give your telegram id.?
