### ISSUE TITLE
Server/Client Mode 

### ISSUE THREAD

**Issue by Chail35** [WanderingPhilosopher/VanBitCrackenRandom2#15]
Hi just a suggestion but it would be nice if you added a Client/Server mode to distribute the work load across clients. Kind of like how it is in Jean Luc Pons Kangaroo Program, also could you make this be able to run in Linux because currently we can’t run cuda based exe files in Linux.

**Comment by WanderingPhilosopher** [comment]
There is a Linux binary now in version 3. Server/client is kind of not needed as this program is pure random, not sequential.
