### ISSUE TITLE
rekey error

### ISSUE THREAD

**Issue by pianist-coder** [WanderingPhilosopher/VanBitCrackenRandom2#17]
Hi, bro. Despite the description of the re key parameter, it gives information in the console, apparently the minimum value is -r 1 is not a million, but a billion)

**Comment by WanderingPhilosopher** [comment]
I have updated the -r; if you use the -r, the integer you use is multiplied by 10,000,000. So if you use a -r 1000000, the program should rekey every 10,000,000,000,000 keys. Had to updated because of faster GPUs.
