### ISSUE TITLE
Saves

### ISSUE THREAD

**Issue by aleksva77** [WanderingPhilosopher/VanBitCrackenRandom2#19]
Is it possible to save?

**Comment by marssystems** [comment]
Yes it is  -o outputfile: Output results to the specified file; Default is KeysFound.txt

**Comment by aleksva77** [comment]
I'm not talking about the result found, but about the result of the work. If suddenly the lights go out, then start from the stopped work.

**Comment by marssystems** [comment]
Its random - so you don't need to save anything.
