### ISSUE TITLE
Divide by 0 error.

### ISSUE THREAD

**Issue by marssystems** [WanderingPhilosopher/VanBitCrackenRandom2#2]
VBCr v2.00
 Search For: 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so [Compressed]
 Started on: Mon Jan 30 14:11:43 2023
 Randomness: New Random Keys Every 1000 Mkeys
  Beg Range: 20000000000000000 (66 bit)
  End Range: 3FFFFFFFFFFFFFFFF (66 bit)
  Rng Width: 1FFFFFFFFFFFFFFFF (65 bit)
CPU Threads: 0
GPU: GPU #0 NVIDIA GeForce GTX 1050 (5x128 cores) Grid(256x256)
Divide by 0!
 [00:06:08:38 Run Time][Total 24.54 MK/s][GPU 24.54 MK/s][Keys 543,648,907,264][Found 0][Rekeys: 540]

I get this 'Divide by 0 ' error when I run the program.

**Comment by WanderingPhilosopher** [comment]
It is caused by that large grid size and small GPU (and possibly PC) memory.
Try to stay in even multiples for x...so for your GPU, try 40x128 or 40x256; something like that.
The program is basically waiting for your GPU to catch up (setting the random key points) so the program can start.

**Comment by marssystems** [comment]
OK - thanks for that. I will change the settings and see how it goes.

My PC is a Gen 9 i7 with 64Gb of RAM - so I know its not that. The graphics card however is a bit sad.

**Comment by whelpw** [comment]
> OK - thanks for that. I will change the settings and see how it goes.
> 
> My PC is a Gen 9 i7 with 64Gb of RAM - so I know its not that. The graphics card however is a bit sad.

C:\Users\User>wmic baseboard get product, Manufacturer, version, serialnumber
Manufacturer                   Product   SerialNumber  Version
Gigabyte Technology Co., Ltd.  P55-US3L
![i3_540](https://user-images.githubusercontent.com/115485264/216340866-0c7e5a04-5be3-4ebb-a338-dc6f1c00964f.jpg)


:-))
