### ISSUE TITLE
Multi GPU error

### ISSUE THREAD

**Issue by whelpw** [WanderingPhilosopher/VanBitCrackenRandom2#3]
Hi !   
Thanks for great porgram!

Get an error when GPU is more than 1:
![VBCr_error](https://user-images.githubusercontent.com/115485264/216305323-4b791626-f7c5-482f-983d-4a56b6ceb089.jpg)

with no key "-gpu" work normally (really, works GREAT)), but only one (first, #0) card. 
Need Help!

P.S.:
-gpu #0,#1,#2 - also don`t work

tks!

**Comment by marssystems** [comment]
You are using the wrong syntax - it should be -

VBCr.exe -t 0 -gpu -gpuId 0,1,2

**Comment by WanderingPhilosopher** [comment]
> You are using the wrong syntax - it should be -
> 
> VBCr.exe -t 0 -gpu -gpuId 0,1,2

Just saw this. Thank you for answering!
