### ISSUE TITLE
Can you please port from cuda to HIP ? So executable will work on AMD gpus ? 

### ISSUE THREAD

**Issue by bballer4life** [WanderingPhilosopher/VanBitCrackenRandom2#6]
Can you please port from CUDA to HIP ? So executable will work on AMD gpus ? 
Rewriting for OpenCL will also work but porting from CUDA to HIP will be much less complicated IMHO.

**Comment by WanderingPhilosopher** [comment]
Brichard is the OpenCL guru. I have no experience with it.
