### ISSUE TITLE
no result range in very very very short range

### ISSUE THREAD

**Issue by mirameshs** [WanderingPhilosopher/VanBitCrackenRandom2#9]
please look at this command 
`VBCr.exe -stop -begr 21111111111111110 -endr 21111111111111120 -dis 1 -drk 1 13zb1hQb`
 my speed is about 10 MK/S
the program after 1 second should notify me that the range is finished but the key not found.
why this program can not scan a range from beggining to end? 

if you run mentioned code, the program always will be running without any result.

**Comment by WanderingPhilosopher** [comment]
This is the random version. It will not stop/search sequentially in a range. I do have the Spread version in my repos.
